### ISSUE TITLE
Enable https

### ISSUE THREAD

**Issue by CendioOssman** [novnc/novnc.github.io#1]
github pages now support TLS/https. Someone needs to update the A records for novnc.com though. @kanaka?

See https://blog.github.com/2018-05-01-github-pages-custom-domains-https/ and https://github.com/TigerVNC/tigervnc.github.io/issues/3.

**Comment by kanaka** [comment]
Okay, I've updated the A records for novnc.com, re-enabled the custom domain and https://novnc.com now seems to load correctly.

```
$ dig +nocomments novnc.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> +nocomments novnc.com
;; global options: +cmd
;novnc.com.			IN	A
novnc.com.		4557	IN	A	185.199.110.153
novnc.com.		4557	IN	A	185.199.108.153
novnc.com.		4557	IN	A	185.199.109.153
novnc.com.		4557	IN	A	185.199.111.153
;; Query time: 27 msec
;; SERVER: 127.0.1.1#53(127.0.1.1)
;; WHEN: Sat Sep 15 12:03:07 CDT 2018
;; MSG SIZE  rcvd: 102
```
