### ISSUE TITLE
SecurityError while attempting to use demo

### ISSUE THREAD

**Issue by ghost** [novnc/novnc.github.io#4]
While attempting to run the demo on novnc.com, I received the following error message:

```
Uncaught SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.

https://novnc.com/noVNC/core/websock.js:231:21

Error: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at Websock.open (https://novnc.com/noVNC/core/websock.js:231:21)
    at RFB._connect (https://novnc.com/noVNC/core/rfb.js:551:24)
    at RFB._updateConnectionState (https://novnc.com/noVNC/core/rfb.js:903:22)
    at new RFB (https://novnc.com/noVNC/core/rfb.js:279:14)
    at HTMLButtonElement.connect (https://novnc.com/noVNC/app/ui.js:1044:18)
```
I am currently using Chrome 118.0.5993.124 on ChromeOS.

![Screenshot 2023-12-04 2 55 29 PM](https://github.com/novnc/novnc.github.io/assets/728562/9255bfbe-4d70-4cb1-975f-f586eda8bcc7)

**Comment by CendioOssman** [comment]
I'm afraid the browsers will not let you mix TLS and non-TLS content. You'll need to set up TLS for the server you are trying to connect to.

The crash is a very unpleasant way to present this, though. So I've added a fix to noVNC to present this case as a normal error message.
